INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 1', 'user1@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 2', 'user2@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 3', 'user3@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 4', 'user4@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 5', 'user5@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 6', 'user6@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 7', 'user7@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('user 8', 'user8@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Teste', 'qualquer@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Fulano', 'teste@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Pedro', 'pedro@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Luciana', 'luciana@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Amanda', 'amanda@email.com', false)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Lucas', 'lucas@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Andre', 'andre@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Cesa', 'cesar@email.com', true)
INSERT INTO PESSOA (NAME, EMAIL, STATUS) VALUES ('Anne', 'anneully@email.com', true)


